name: Deploy to Production

on:
  push:
    branches:
      - master

env:
  NODE_ENV: production

jobs:
  build:
    name: Build for Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: Setup Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install dependencies
        run: yarn install --production=false --frozen-lockfile

      - name: Build static files
        run: yarn build
        env:
          FLAMELINK_ENV: staging
          SITE_URL: https://flamelink-website-jan-2020.web.app
          FIREBASE_CONFIG_PK: ${{ secrets.FIREBASE_CONFIG_PK }}

      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: public
          path: public

  deploy:
    name: Deploy to Production
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Download Production Artifact
        uses: actions/download-artifact@master
        with:
          name: public

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:flamelink-website-jan-2020
        env:
          PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
