name: Deploy Website

on:
  push:
    branches:
      - master
      - develop

env:
  NODE_ENV: production

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification - Build Starting
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_NOTIFICATION_CHANNEL }}
          SLACK_COLOR: '#28a745'
          SLACK_ICON: ':robot_face:'
          SLACK_MESSAGE: 'Build starting for *${{ github.ref }}* branch...'
          SLACK_TITLE: Website Build
          SLACK_USERNAME: GithubBot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: Setup Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install dependencies
        run: yarn install --production=false --frozen-lockfile

      - name: Build static files (Production)
        if: github.ref == 'refs/heads/master'
        run: yarn build
        env:
          FLAMELINK_ENV: production
          SITE_URL: https://flamelink.io
          FIREBASE_CONFIG_PK: ${{ secrets.FIREBASE_CONFIG_PK }}
          GATSBY_FIREBASE_CONFIG_API_KEY: ${{ secrets.GATSBY_FIREBASE_CONFIG_API_KEY }}
          GATSBY_FIREBASE_CONFIG_AUTH_DOMAIN: ${{ secrets.GATSBY_FIREBASE_CONFIG_AUTH_DOMAIN }}
          GATSBY_FIREBASE_CONFIG_DATABASE_URL: ${{ secrets.GATSBY_FIREBASE_CONFIG_DATABASE_URL }}
          GATSBY_FIREBASE_CONFIG_PROJECT_ID: ${{ secrets.GATSBY_FIREBASE_CONFIG_PROJECT_ID }}
          GATSBY_FIREBASE_CONFIG_STORAGE_BUCKET: ${{ secrets.GATSBY_FIREBASE_CONFIG_STORAGE_BUCKET }}
          GATSBY_FIREBASE_CONFIG_MESSAGING_SENDER_ID: ${{ secrets.GATSBY_FIREBASE_CONFIG_MESSAGING_SENDER_ID }}
          GATSBY_FIREBASE_CONFIG_APP_ID: ${{ secrets.GATSBY_FIREBASE_CONFIG_APP_ID }}
          GOOGLE_ANALYTICS_TRACKING_ID: ${{ secrets.GOOGLE_ANALYTICS_TRACKING_ID }}
          GTM_TRACKING_ID: ${{ secrets.GTM_TRACKING_ID }}
          GATSBY_TYPEFORM_SOLAR_FLARE_URL: ${{ secrets.GATSBY_TYPEFORM_SOLAR_FLARE_URL }}
          GATSBY_SENTRY_DSN: ${{ secrets.GATSBY_SENTRY_DSN }}
          LINKEDIN_PARTNER_ID: ${{ secrets.LINKEDIN_PARTNER_ID }}

      - name: Build static files (Staging)
        if: github.ref == 'refs/heads/develop'
        run: yarn build
        env:
          FLAMELINK_ENV: staging
          SITE_URL: https://flamelink-staging.web.app
          FIREBASE_CONFIG_PK: ${{ secrets.FIREBASE_CONFIG_PK }}
          GATSBY_FIREBASE_CONFIG_API_KEY: ${{ secrets.GATSBY_FIREBASE_CONFIG_API_KEY }}
          GATSBY_FIREBASE_CONFIG_AUTH_DOMAIN: ${{ secrets.GATSBY_FIREBASE_CONFIG_AUTH_DOMAIN }}
          GATSBY_FIREBASE_CONFIG_DATABASE_URL: ${{ secrets.GATSBY_FIREBASE_CONFIG_DATABASE_URL }}
          GATSBY_FIREBASE_CONFIG_PROJECT_ID: ${{ secrets.GATSBY_FIREBASE_CONFIG_PROJECT_ID }}
          GATSBY_FIREBASE_CONFIG_STORAGE_BUCKET: ${{ secrets.GATSBY_FIREBASE_CONFIG_STORAGE_BUCKET }}
          GATSBY_FIREBASE_CONFIG_MESSAGING_SENDER_ID: ${{ secrets.GATSBY_FIREBASE_CONFIG_MESSAGING_SENDER_ID }}
          GATSBY_FIREBASE_CONFIG_APP_ID: ${{ secrets.GATSBY_FIREBASE_CONFIG_APP_ID }}
          GATSBY_TYPEFORM_SOLAR_FLARE_URL: ${{ secrets.GATSBY_TYPEFORM_SOLAR_FLARE_URL }}
          GATSBY_SENTRY_DSN: ${{ secrets.GATSBY_SENTRY_DSN }}
          GTM_TRACKING_ID: ${{ secrets.GTM_TRACKING_ID }}

      - name: Archive Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: public

      - name: Slack Notification - Build Failure
        if: failure()
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_NOTIFICATION_CHANNEL }}
          SLACK_COLOR: '#d73a49'
          SLACK_ICON: ':robot_face:'
          SLACK_MESSAGE: 'Build failed for *${{ github.ref }}* branch'
          SLACK_TITLE: Website Build Failure
          SLACK_USERNAME: GithubBot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Slack Notification - Build Cancelled
        if: cancelled()
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_NOTIFICATION_CHANNEL }}
          SLACK_COLOR: '#e36209'
          SLACK_ICON: ':robot_face:'
          SLACK_MESSAGE: 'Build cancelled for *${{ github.ref }}* branch'
          SLACK_TITLE: Website Build Cancelled
          SLACK_USERNAME: GithubBot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification - Deployment Starting
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_NOTIFICATION_CHANNEL }}
          SLACK_COLOR: '#28a745'
          SLACK_ICON: ':robot_face:'
          SLACK_MESSAGE: 'Deployment starting for *${{ github.ref }}* branch...'
          SLACK_TITLE: Website Deployment
          SLACK_USERNAME: GithubBot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Download Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: public
          path: public

      - name: Deploy to Firebase Hosting (Production)
        if: github.ref == 'refs/heads/master'
        uses: w9jds/firebase-action@v1.3.1
        with:
          args: deploy --only hosting:production
        env:
          PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Deploy to Firebase Hosting (Staging)
        if: github.ref == 'refs/heads/develop'
        uses: w9jds/firebase-action@v1.3.1
        with:
          args: deploy --only hosting:staging
        env:
          PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Slack Notification - Deployment Success
        if: success()
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_NOTIFICATION_CHANNEL }}
          SLACK_COLOR: '#28a745'
          SLACK_ICON: ':robot_face:'
          SLACK_MESSAGE: 'Deployment succeeded for *${{ github.ref }}* branch'
          SLACK_TITLE: Website Deployment Success
          SLACK_USERNAME: GithubBot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Slack Notification - Deployment Failure
        if: failure()
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_NOTIFICATION_CHANNEL }}
          SLACK_COLOR: '#d73a49'
          SLACK_ICON: ':robot_face:'
          SLACK_MESSAGE: 'Deployment failed for *${{ github.ref }}* branch'
          SLACK_TITLE: Website Deployment Failure
          SLACK_USERNAME: GithubBot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Slack Notification - Deployment Cancelled
        if: cancelled()
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_NOTIFICATION_CHANNEL }}
          SLACK_COLOR: '#e36209'
          SLACK_ICON: ':robot_face:'
          SLACK_MESSAGE: 'Deployment cancelled for *${{ github.ref }}* branch'
          SLACK_TITLE: Website Deployment Cancelled
          SLACK_USERNAME: GithubBot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
